name: Greep
description:
avatar: /img/icon.png

socials:
  mail: greep@greep.fr
  github: GreepTheSheep
  twitter: GreepTheSheep
  mastodon:
    username: "@greep"
    url: https://mastodon.imagisphe.re/
  threads: greepthesheep
  patreon: Greep
  linkedin: matthieu-dehon
  youtube: GreepTheSheep
  twitch: GreepTheSheep
